### ISSUE TITLE
File label.txt

### ISSUE THREAD

**Issue by tanbuinhat** [QJYBall/MyoPS-Net#1]
Hi, can I ask about file "train.txt" in the dataset organization? Since I download the MyoPS 2020 dataset and it doesn't have any file txt. Can you give an example about file txt

**Comment by QJYBall** [comment]
Thank you for your interest!

We have added a folder **_examples_** with file **_train20.txt, validation5.txt and test.csv_** for reference.

Besides, as we mentioned in the readme file, you should organize the dataset as the following structure:
```
data/
  -- train_set/
     -- train_image/
     -- train_gd/
  -- val_set/     
     -- val_image/
     -- val_gd/
  -- test_set/
     -- test_image/
  -- train.txt (with each line: image_path gd_path z_index)
  -- validation.txt (with each line: image_path gd_path z_index)
  -- test.csv (with each line: image_path stage dx dy dz)

**Comment by tanbuinhat** [comment]
Thanks you so much!
