### ISSUE TITLE
MyoPS 数据集问题

### ISSUE THREAD

**Issue by hexiao0275** [QJYBall/MyoPS-Net#2]
我们下载了MICCAI2020 MyoPS Challenge发现没有LGE，T1m的数据，只有T1,T2,DE。如能提供，我将不胜感激！ 电子邮件：xiaoh@cug.edu.cn

**Comment by QJYBall** [comment]
您好，MICCAI2020 MyoPS
Challenge数据集中只包含了LGE(也就是DE)、T2、bSSFP三种模态的影像数据，这个是公开的；然后在文章中我们使用的另一个数据集含有LGE、T2、bSSFP、T1m、T2*m五种模态，但由于这个数据来自于合作的医院，可能不太方便公开，不好意思！

**Comment by QJYBall** [comment]
您好，在这篇期刊文章中主要使用了两个数据集：
1、MICCAI2020 MyoPS Challenge数据集：只包含bSSFP、LGE(也就是DE)、T2三种序列的影像数据，这个是公开的；
2、私人数据集：在文章中我们使用的另一个数据集含有LGE、T2、bSSFP、T1m、T2*m五种模态，但由于这个数据来自于合作的医院，可能不太方便公开，不好意思！

**Comment by hexiao0275** [comment]
非常感谢您详细的回复，我还想知道在得到最终的nii.gz的结果后怎么论文中的可视化结果呢。 电子邮件：[xiaoh@cug.edu.cn](mailto:xiaoh@cug.edu.cn)
